services:
  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_user
      - backend_book
      - backend_loan

  backend_user:
    container_name: backend_user
    build:
      context: ./userService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URI=mongodb://mongodb_user:27017/phase2
      - LOAN_BACKEND_BASE_URI=http://backend_loan:3003
    depends_on:
      - mongodb_user

  backend_book:
    container_name: backend_book
    build:
      context: ./bookService
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URI=mongodb://mongodb_book:27017/phase2
      - LOAN_BACKEND_BASE_URI=http://backend_loan:3003
    depends_on:
      - mongodb_book

  backend_loan:
    container_name: backend_loan
    build:
      context: ./loanService
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URI=mongodb://mongodb_loan:27017/phase2
      - BOOK_BACKEND_BASE_URI=http://backend_book:3002
      - USER_BACKEND_BASE_URI=http://backend_user:3001
    depends_on:
      - mongodb_loan

  mongodb_user:
    container_name: mongo_user
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - user_data:/data/db
  
  mongodb_book:
    container_name: mongo_book
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - book_data:/data/db

  mongodb_loan:
    container_name: mongo_loan
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - loan_data:/data/db

volumes:
  user_data:
  book_data:
  loan_data: