http {
    server {
        listen       80;
        server_name  localhost;

        location /api/users {
            proxy_pass http://backend_user:3001/api/users;
        }

        location /api/books {
            proxy_pass http://backend_book:3002/api/books;
        }

        location /api/loans {
            proxy_pass http://backend_loan:3003/api/loans;
        }
    }
}