user www-data;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server backend_user:3001;
    }

    upstream book_service {
        server backend_book:3002;
    }

    upstream loan_service {
        server backend_loan:3003;
    }

    server {
        listen 80;
        server_name library.com;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /api/users/ {
            proxy_pass http://user_service/api/users/;
        }

        location /api/books/ {
            proxy_pass http://book_service/api/books/;
        }

        location /api/loans/ {
            proxy_pass http://loan_service/api/loans/;
        }

        location / {
            return 404;
        }

        error_page 502 503 504 /50x.html;
        location = /50x.html {
            return 503 '{"error": "Service temporarily unavailable"}';
            add_header Content-Type application/json;
        }
    }
}